<template>
  <div class="container flex-col items-center">

        <div id="encabezado" align="center">
            <br><br><br><br><br><br><br><br><br><br>
            <h3 class="display-6">
                Lista de Regalos de
                <br> Matthew Del Rio Hoyones
            </h3>

        </div>

        <br><br><br><br><br>

        <table class="table table-striped " width="70%">
            <thead>

                <tr>

                    <th class="text-center" scope="col">No.</th>
                    <th class="text-center" scope="col" align="center">REGALO</th>
                    <th class="text-center" scope="col" align="center">FOTO</th>
                    <th class="text-center" scope="col" align="center">PARTICIPANTE</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row" class="align-middle text-center">1</th>
                    <td class="align-middle ">Cama Cuna Blanca</td>
                    <td class="align-middle text-center"><img src="https://falabella.scene7.com/is/image/FalabellaCO/4312713?wid=249&amp;hei=249&amp;qlt=70" width="100" height="100"></td>
                    <td class="align-middle text-center" align="center">
                        <button class="btn btn-primary">
                Ana Lucia
            </button>
                    </td>
                </tr>
                <tr>
                    <th scope="row" class="align-middle text-center">2</th>
                    <td class="align-middle ">Coche Deportivo Color Rojo</td>
                    <td class="align-middle text-center "><img src="https://pepeganga.vteximg.com.br/arquivos/ids/213857-600-600/617741-1.jpg?v=636078330270470000" width="100" height="100"></td>
                    <td class="align-middle text-center">
                        <button class="btn btn-primary">
                Edgar Del Rio
                </button>
                    </td>
                </tr>
                <tr>
                    <th class="align-middle text-center" scope="row">3</th>
                    <td class="align-middle ">Pijamas ( blanca, gris, azul)</td>
                    <td class="align-middle text-center"><img src="https://images-na.ssl-images-amazon.com/images/I/81xonfmkYfL._AC_SX679_.jpg" alt="" width="100"></td>
                    <td class="align-middle text-center">
                        <button class="btn btn-primary">
                Michell
            </button>
                    </td>
                </tr>
                <tr>
                    <th class="align-middle text-center " scope="row">4</th>
                    <td class="align-middle ">Toallas de algodon</td>
                    <td class="align-middle text-center"><img src="https://i0.wp.com/ae01.alicdn.com/kf/HTB1zPcwLxTpK1RjSZFMq6zG_VXak/Reci%C3%A9n-Nacido-bolsa-de-dormir-de-silicona-manta-beb%C3%A9-reci%C3%A9n-nacidos-toallas-de-algod%C3%B3n-de-Primavera.jpg_350x350.jpg" width="100" height="100"></td>
                    <td class="align-middle text-center"><button class="btn btn-warning">Disponible</button></td>
                </tr>
                <tr>
                    <th class="align-middle text-center" scope="row">5</th>
                    <td class="align-middle ">Pañalera</td>
                    <td class="align-middle text-center"><img src="https://bebemundo.com.sv/wp-content/uploads/2018/09/92097-600x600.jpg" width="100" height="100"></td>
                    <td class="align-middle text-center"><button class="btn btn-primary">Bienvenida Tapias</button></td>
                </tr>
                <tr>
                    <th class="align-middle text-center" scope="row">6</th>
                    <td class="align-middle ">Juego de Sabana (blanco, gris o azul)</td>
                    <td class="align-middle text-center">
                        <img src="https://mla-s2-p.mlstatic.com/488025-MLA25381389731_022017-O.jpg" width=" 100 " height="100 "></td>
                    <td class="align-middle text-center"><button class="btn btn-warning ">Disponible</button></td>
                </tr>
                <tr>
                    <th class="align-middle text-center" scope="row">7</th>
                    <td class="align-middle ">Mantas (blanco, gris o azul)</td>
                    <td class="align-middle text-center">
                        <img src="https://i.pinimg.com/originals/88/6c/55/886c55e1c37330e3f66bdc65bfbe1b29.jpg" width=" 100 " height="100 "></td>
                    <td class="align-middle text-center"><button class="btn btn-warning ">Disponible</button></td>
                </tr>
                <tr>
                    <th class="align-middle text-center" scope="row">8</th>
                    <td class="align-middle ">Body y pantalon (blanco, gris o azul) </td>
                    <td class="align-middle text-center">
                        <img src="https://miangelito.com.co/1243-large_default/set-x-3-para-bebe-nino-conjuntos-body-y-pantalon.jpg" width=" 100 " height="100 "></td>
                    <td class="align-middle text-center"><button class="btn btn-warning ">Disponible</button></td>
                </tr>
            </tbody>
        </table>
    </div>
</template>
